"""add error_type to generation_jobs

Revision ID: 3bac8ec7a505
Revises: a1c3d9f7e2b4
Create Date: 2026-08-15 08:33:55.102603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3bac8ec7a505'
down_revision: Union[str, None] = 'a1c3d9f7e2b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_jobs', sa.Column('error_type', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generation_jobs', 'error_type')
    # ### end Alembic commands ###
