"""add knowledge analyses

Revision ID: 508a2e74f7c0
Revises: 553af5fa8740
Create Date: 2026-08-14 10:03:46.608142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '508a2e74f7c0'
down_revision: Union[str, None] = '553af5fa8740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_analyses',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('completed', 'failed', name='knowledge_analysis_status'), nullable=False),
    sa.Column('error', sa.String(length=1024), nullable=True),
    sa.Column('existing_summary', sa.Text(), nullable=True),
    sa.Column('missing_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommended_additions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('duplicate_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outdated_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_analyses_project_id'), 'knowledge_analyses', ['project_id'], unique=False)
    op.create_index(op.f('ix_knowledge_analyses_user_id'), 'knowledge_analyses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_analyses_user_id'), table_name='knowledge_analyses')
    op.drop_index(op.f('ix_knowledge_analyses_project_id'), table_name='knowledge_analyses')
    op.drop_table('knowledge_analyses')
    # ### end Alembic commands ###
