"""add websites table

Revision ID: aed8fdc31b7f
Revises: 6e2c1a9b4f7d
Create Date: 2026-08-17 06:16:03.542019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'aed8fdc31b7f'
down_revision: Union[str, None] = '6e2c1a9b4f7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('websites',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('style', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('completed', 'failed', name='website_status'), nullable=False),
    sa.Column('error', sa.String(length=1024), nullable=True),
    sa.Column('pages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deployment_provider', sa.String(length=32), nullable=True),
    sa.Column('deployment_storage_ref', sa.String(length=1024), nullable=True),
    sa.Column('deployment_live_url', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_websites_project_id'), 'websites', ['project_id'], unique=False)
    op.create_index(op.f('ix_websites_user_id'), 'websites', ['user_id'], unique=False)
    # NOTE: autogenerate also proposed dropping the composite
    # (user_id, sort_column) indexes added in Phase 11
    # (354955ab3d28_add_composite_user_id_sort_column_indexes) — a known
    # false positive (those were created with raw SQL, so their reflected
    # form doesn't diff-match the SQLAlchemy Index() metadata cleanly).
    # Deliberately not applying those drops here; only the real
    # 'websites' table addition above is kept.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_websites_user_id'), table_name='websites')
    op.drop_index(op.f('ix_websites_project_id'), table_name='websites')
    op.drop_table('websites')
    # ### end Alembic commands ###
