"""add projects and history entries

Revision ID: fe6de1823544
Revises: c4d49fb3eeb4
Create Date: 2026-08-14 06:39:12.511875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fe6de1823544'
down_revision: Union[str, None] = 'c4d49fb3eeb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', name='project_status'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('history_entries',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('chat', 'image', 'video', 'audio', 'document', 'website', 'poster', 'logo', 'deployment', 'knowledge_update', name='history_entry_type'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'processing', 'completed', 'failed', name='history_entry_status'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('output_ref', sa.String(length=1024), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_entries_project_id'), 'history_entries', ['project_id'], unique=False)
    op.create_index(op.f('ix_history_entries_status'), 'history_entries', ['status'], unique=False)
    op.create_index(op.f('ix_history_entries_type'), 'history_entries', ['type'], unique=False)
    op.create_index(op.f('ix_history_entries_user_id'), 'history_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_history_entries_user_id'), table_name='history_entries')
    op.drop_index(op.f('ix_history_entries_type'), table_name='history_entries')
    op.drop_index(op.f('ix_history_entries_status'), table_name='history_entries')
    op.drop_index(op.f('ix_history_entries_project_id'), table_name='history_entries')
    op.drop_table('history_entries')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
